config/routes.rb
Cormacksdesk::Application.routes.draw do

  root 'welcome#index'

  get 'cases' => 'cases#index'
  patch 'cases' => 'cases#update'
  get 'cases/edit' => 'cases#edit'

  get 'labels' => 'labels#index'
  post 'labels' => 'labels#create'
  get 'labels/new' => 'labels#new'

end

app/models/case.rb
class Case
  include ActiveModel::Model
  extend ActiveModel::Naming

  attr_accessor :the_case, :labels

  def initialize attributes = {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def save
    begin
      the_case.update(labels: labels, label_action: :replace)
      true
    rescue DeskApi::Error::UnprocessableEntity => e
      e.errors.each do |an_error|
        errors.add(an_error[0].to_sym, error_string(an_error[1]))
      end
      false
    rescue DeskApi::Error => e
      errors.add(e.class.name, e.to_s)
      false
    end
  end

  def persisted?
    false
  end

  private
  def error_string error_array
    if error_array && error_array.any?
      results = " is " + error_array.to_sentence
    else
      ""
    end
  end
end

app/models/label.rb
class Label
  include ActiveModel::Model
  extend ActiveModel::Naming

  attr_accessor :name, :description, :types, :enabled, :color

  def initialize attributes = {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def attribute_hash
    {
      name: name,
      description: description,
      types: types,
      enabled: enabled,
      color: color
    }
  end

  def save
    begin
      new_label = ApplicationController.helpers.desk.labels.create(attribute_hash)
      true
    rescue DeskApi::Error::UnprocessableEntity => e
      e.errors.each do |an_error|
        errors.add(an_error[0].to_sym, error_string(an_error[1]))
      end
      false
    rescue DeskApi::Error => e
      errors.add(e.class.name, e.to_s)
      false
    end
  end

  def persisted?
    false
  end

  private
  def error_string error_array
    if error_array && error_array.any?
      results = " is " + error_array.to_sentence
    else
      ""
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    begin
      puts "filter position: " + params[:filter_id].to_s
      @filter = get_filter(params[:filter_id])
      @cases = get_cases(@filter)
    rescue DeskApi::Error => e
      @errors= {e.to_s => e.backtrace.inspect}
    end
  end

  def edit
    @case = get_a_case(params[:id])
    if @case.locked_until.present?
      puts "this case is locked!"
    end
    @case_model = Case.new({
      the_case: @case,
      labels: @case.labels.entries.map(&:name)
    })
    @labels = get_labels
  end

  def update
    puts "filter index in update: " + params[:filter_id].to_s
    @case = get_a_case(params[:case][:id])
    @case_model = Case.new({
      the_case: @case,
      labels: params[:case].present? ? params[:case][:labels] : []
    })
    @labels = get_labels

    if @case_model.save
      redirect_to action: 'index', filter_id: params[:filter_id]
    else
      render action: 'edit', filter_id: params[:filter_id]
    end
  end

  private

  def get_desk
    ApplicationController.helpers.desk
  end

  def get_filter index = nil
    filter = nil
    begin
      filter = get_desk.filters.entries[(index.to_i-1)]
    rescue => e
      puts e
      filter = get_desk.filters.entries.first
    end
    filter = get_desk.filters.entries.first if filter.nil?
    filter
  end

  def get_cases filter = nil
    if filter.present?
      filter.cases
    else
      get_filter.cases
    end
  end

  def get_a_case id
    get_desk.cases.find(id)
  end

  def get_labels
    get_desk.labels.entries
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    @labels = view_context.desk.labels.entries
  end

  def new
    @label = Label.new()
  end

  def create
    @label = Label.new(params[:label])
    # ({
    #   name: params[:label][:name],
    #   description: params[:label][:description],
    #   types: params[:label][:types],
    #   enabled: params[:label][:enabled],
    #   color: params[:label][:color]
    # })

    if @label.save
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @filters = view_context.desk.filters.entries
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def desk
    @client ||= DeskApi::Client.new({
      token: 'gT0DSxcvg1OksCledWnq',
      token_secret: 'V1hITFDNMbi4yARZ5mV0OFXw9htu3628eEUVLBAv',
      consumer_key: '0GqJJNW3dt03dsbqWIWr',
      consumer_secret: '1eMmEFvcAv8WISkK2LfFlqZPlNPVxZ9aN23Hbyus',
      subdomain: 'pcconsulting'
    })
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
  def label_colors
    [
      "default",
      "blue",
      "white",
      "yellow",
      "red",
      "orange",
      "green",
      "black",
      "purple",
      "brown",
      "grey",
      "pink"
    ]
  end

  def color_style_text color
    case color
    when "default"
      bg_color = 'lightgray'
      text_color = 'black'
    when "blue"
      bg_color = 'deepskyblue'
      text_color = 'white'
    when "white"
      bg_color = 'white'
      text_color = 'black'
    when "yellow"
      bg_color = 'lightgoldenrodyellow'
      text_color = 'black'
    when "red"
      bg_color = 'red'
      text_color = 'white'
    when "orange"
      bg_color = 'orange'
      text_color = 'white'
    when "green"
      bg_color = 'green'
      text_color = 'white'
    when "black"
      bg_color = 'black'
      text_color = 'white'
    when "purple"
      bg_color = 'purple'
      text_color = 'white'
    when "brown"
      bg_color = 'brown'
      text_color = 'white'
    when "grey"
      bg_color = 'gray'
      text_color = 'white'
    when "pink"
      bg_color = 'pink'
      text_color = 'darkpink'
    else
      bg_color = 'white'
      text_color = color
    end

    "background-color:" + bg_color.to_s + ";color:" + text_color.to_s + ";"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def count_filter_cases(filter)
    filter.cases.entries.count.to_s
  end
end

app/views/cases/_errors.html.erb
<% if @case_model.errors.full_messages.any? %>
  <div style="color:red">
    <h3>This Case could not be updated because of the following errors:</h3>
    <ul>
      <% @case_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/cases/edit.html.erb
<%= render partial: 'errors' %>

<h3>Choose the labels you want to have on the "<%= @case.subject %>" case (ID: <%= @case.id %>):</h3>

<%= simple_form_for @case_model, method: :patch do |f| %>
  <%= hidden_field_tag :filter_id, params[:filter_id].to_s %>
  <p>
    <%= f.input :id, as: :hidden, input_html: { value: @case.id } %>
    <%= f.input :labels, label: "", as: :check_boxes, collection: @labels, selected: @case.labels.entries, value_method: :name %>
  </p>
  <br>
  <%= f.submit "Update Labels" %>
<% end %>

<h3><%= link_to "Back to Cases", cases_path(filter_id: params[:filter_id]) %></h3>

app/views/cases/index.html.erb
<% if @errors %>
  <div style="color:red">
    <h3><%= @errors %></h3>
  </div>
<% else %>
  <h2>All Cases with the "<%= @filter.name %>" filter</h2>

  <% if @cases.entries.any? %>
    <table>
      <tr>
        <th>Subject</th>
        <th>Labels</th>
        <th></th>
      </tr>
      <% @cases.entries.each do |a_case| %>
        <tr>
          <td style="text-align:right; vertical_align:center; padding:15px;"><strong><%= a_case.subject %></strong></td>
          <td style="text-align:center; vertical-align:center; padding:15px"><%= a_case.labels.entries.map{|label| label.name}.join(", ") %></td>
          <td style="text-align:left; vertical-align:center; padding:15px;"><%= link_to "Manage Labels", controller: "cases", action: "edit", id: a_case.id, filter_id: params[:filter_id] %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h3>Sorry, but there are no cases with this filter.
  <% end %>
<% end %>

<h3><%= link_to "Back Home", root_path %></h3>

app/views/labels/_errors.html.erb
<% if @label.errors.full_messages.any? %>
  <div style="color:red">
    <h3>This Label could not be saved because of the following errors:</h3>
    <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/labels/index.html.erb
<h2>All of the Labels!</h2>

<h3><%= link_to "Create a new Label", controller: "labels", action: "new" %></h3>

<table style="width:75%">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Types</th>
    <th></th>
  <% @labels.each do |a_label| %>
    <tr style=<%= color_style_text(a_label.color) %> >
      <td><%= a_label.name %></td>
      <td><%= a_label.description %></td>
      <td><%= a_label.types.entries.join(", ") %></td>
      <td><%= a_label.enabled ? "Enabled" : "Disabled" %></td>
    </tr>
  <% end %>
</table>

<h3><%= link_to "Back Home", root_path %></h3>

app/views/labels/new.html.erb
<%= render partial: "errors" %>

<%= link_to "Back to Labels", labels_path %>

<%= form_for @label do |f| %>
  <p>
    <h5>Label Name:</h5>
    <%= f.text_field :name %>
  </p>
  <p>
    <h5>Description:</h5>
    <%= f.text_area :description %>
  </p>
  <p>
    <h5>Types</h5>
    <%= check_box_tag "label[types][]", "case", false %>case
    <%= check_box_tag "label[types][]", "macro", false %>macro
    <%= check_box_tag "label[types][]", "article", false %>article
  </p>
  <p>
    <h5>Enabled?</h5>
    <%= radio_button_tag 'label[enabled]', true, true %>Yes
    <%= radio_button_tag 'label[enabled]', false %>No
  </p>
  <p>
    <h5>Choose a Color:</h5>
    <%= select "label", "color", label_colors %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cormack's Desk</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Cormack's Desk!</h1>
<h3>Click a Filter to see the associated cases</h3>

<table>
  <tr>
    <th>Filter Name</th>
    <th>Cases</th>
    <th></th>
  </tr>
  <% @filters.entries.each do |filter| %>
    <tr>
      <td style="text-align:left; vertical_align:center; padding:15px;"><strong><%= link_to(filter.name, cases_path(filter_id: filter.position)) %></strong></td>
      <td style="text-align:left; vertical_align:center; padding:15px;"<strong><%= count_filter_cases(filter) %></strong></td>
    </tr>
  <% end %>
</table>

<h3><%= link_to "View all Labels", labels_path %></h3>